[package]
name = "rpc_state_reader"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
starknet_in_rust = { path = "../", version = "0.3.0" }
ureq = { version = "2.7.1", features = ["json"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = { version = "1.0", features = [
    "arbitrary_precision",
    "raw_value",
] }
starknet_api = { workspace = true }
cairo-lang-starknet = "2.1.0-rc2"
starknet = { workspace = true }
thiserror = { workspace = true }
serde_with = "3.0.0"
dotenv = "0.15.0"
